### PR TITLE
WIP: Airfoil fins normal force coefficient derivative calculation.

### PR DESCRIPTION
**Pull request by MateusStano**
## Pull request type

Please check the type of change your PR introduces:

- [x] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [ ] Spelling has been verified
  - [ ] Code docs are working correctly 

- Code base maintenance (refactoring, formatting, renaming):

  - [ ] Docs have been reviewed and added / updated if needed
  - [ ] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [ ] All tests (`pytest --runslow`) have passed locally

- Code base additions (for bug fixes / features):

  - [ ] Tests for the changes have been added
  - [x] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

The current calculation of the normal force coefficient derivative for airfoil fins assumes that the term where the derivative of the lift coefficient is multiplied by alpha is a constant value. However, for curves that are not linear that simplification does not apply due to another intermediate derivative term.

## What is the new behavior?

The calculations now use a generic formula of the lift coefficient derivative based on thin airfoil theory, which is more in the lines of what Barrowman showed in his paper.  This calculation works for any fin shape, with airfoil or not. It is not as exact as the formula that is currently used for trapezoidal fins but is a good approximation.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Since the new calculation of the lift coefficient derivative takes into account the number of Mach I had to change a bit more of the code than just what relates to the fins. The changes are nothing major but they can be useful when adding supersonic calculations. I also made a pdf with more in-depth documentation.

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
A masterpiece!!!!!!!!!!!!!!!!!!!!!!!!! @MateusStano thanks for showing up... Great contribution

" It is not as exact as the formula that is currently used for trapezoidal fins but is a good approximation."
- Do you have the equations with you? Could you share with us (if it is of easy access)?

**Comment by MateusStano** [comment]
> * Do you have the equations with you? Could you share with us (if it is of easy access)?

The equations are documented here: docs/technical/aerodynamics/Fins_Lift_Coefficient.pdf

I wrote as an explanation/documentation.  I don't know if its any good but everything I used should be in there

**Comment by Gui-FernandesBR** [comment]
Great Stano, really appreciate your expertise writing this document, it will definetely help a lot!

I think the best candidates to revivew the calculations here are @Lucas-KB and @lucasfourier , as they were working on aerodynamic. Perhaps in the next week they will be able to review and merge.

Otherwise, I hope @giovaniceotto could hep earlier, or evene @brunosorban

**Comment by MateusStano** [comment]
> * it does not make sence to set interpolation and extrapolation methods.

Ah good to know! Will change that right now

> One question: how different are equations 6 and 15 of the theory you submitted? In termos of relative change, what's the percentage difference for a typical fin?

The difference seems to be that equation 6 gives a result 63% smaller then equation 15. In other words, the lift generated by the airfoils is 63% bigger than with trapezoildal plane fins.

Here is a comparison with the compareFunction method:
image

The yellow line is the airfoiled one.

**Comment by giovaniceotto** [comment]
To be honest, I am quite intrigued by the difference. I would like to first review this difference before proceeding to merging this PR.

**Pull request merged**
