### PR TITLE
Bug: Issue 115 static margin stability

### PR DESCRIPTION
**Pull request by Lucas-KB**
## Pull request type

Please check the type of change your PR introduces:

- [x] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- Code base additions (for bug fixes / features):

  - [x] Tests for the changes have been added
  - [x] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

Negative static margins result in stable flights (see issue #115).

## What is the new behavior?

RocketPy will no longer support airfoiled fins (for now) and the changes in the pull request #47 were removed. The stability calculations work as expected now. See the image below

Figure_1

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

Simulations considering airfoiled fins will no longer work (until it is reimplemented).

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Is the automatic tests already working properly, @giovaniceotto ? Or do you need more time to finnish it?

**Comment by Lucas-KB** [comment]
I have implemented the tests me, @giovaniceotto, @FranzYuri, and @lucasfourier discussed yesterday. I was just unsure on what to check when the static margin is zero, so I just didn't check anything, but feel free to suggest alternatives and comment on my solution.

**Comment by giovaniceotto** [comment]
@Lucas-KB, would you like to keep the `stability_check.ipynb` file or can we remove it?

**Review by giovaniceotto — APPROVED** [review]

**Comment by giovaniceotto** [comment]
@Lucas-KB, I have added the following changes:

- Refactored the test implementation using [pytest parametrize](https://docs.pytest.org/en/6.2.x/parametrize.html) so that it is shorter and easier to understand.
- Checked if M1 or M2 were very small (< 1e-10 in abs value) in case the static margin was zero.
- Fixed an error where the angle of attack appeared twice in the lift calculation (probably a typo when reverting changes).

Found the last one when checking conflicts before merging (phew...). Now, the plots look much better. In the near future, I would say we need to implement tests that check the natural frequency and damping coefficient, so that errors like these are also caught. However, as the bug we are solving is quite important, I believe we need to merge this PR asap and leave that for another one.

**Review by Gui-FernandesBR — APPROVED** [review]

**Comment by Gui-FernandesBR** [comment]
It's fine by me,

but please let's wait 1 day until merging because Stano asked us to merge # 122 first, I believe there will be no problem.

Regarding the stability_check, I deleted from this PR but uploaded on cloud so we don't loose that masterpiece

**Pull request merged**
