### PR TITLE
ENH: Environment Analysis - Example Notebook

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:

- [X] Code base additions (bugfix, features)

## Pull request checklist

  - [X] Spelling has been verified
  - [X] Code docs are working correctly 

- Code base maintenance (refactoring, formatting, renaming):

  - [x] Docs have been reviewed and added / updated if needed
  - [X] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [X] All tests (`pytest --runslow`) have passed locally

- Code base additions (for bug fixes / features):

  - [ ] Tests for the changes have been added
  - [X] Docs have been reviewed and added / updated if needed
  - [X] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [X] All tests (`pytest --runslow`) have passed locally

## What is the new behavior?
I'm adding the notebook of class usage example with regards of Environment Analysis class

## Does this introduce a breaking change?

- [X] No

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Here are some things I'd like to point before we proceed with approve/merge:

1. There are some functions currently not working (and I can't say why this is happennig) not just on the notebook but in the entire `environment_analysis` branch. Here they are listed: 
3. When I try to set the following arguments `start_date=datetime(2002, 1, 1), end_date=datetime(2021, 12,30)` to the EnvironmentAnalysis Class I face the problem of having only 3 different hours on the output side (18:00, 20:00, 22:00). I can't understand why this bug happen, but changing the dates to both start and finnish in june months has fixed temporarily.
4. There are some TODO along the notebook and EnvironmentAnalysis.py file. I already addressed what I was able to understand and solve (this not include the TODO regarding new tests creation which are not a priority right now).
5. Perhaps @PatrickSampaioUSP wants to create another branch to work on his _voila_ integration after this PR.

@giovaniceotto could you review this PR please?

**Comment by giovaniceotto** [comment]
> @giovaniceotto could you review this PR please?

I will review this PR soon (most likely by thursday, 2022.06.09) and make changes to attempt to solve the bugs that are happening.

**Comment by Gui-FernandesBR** [comment]
@giovaniceotto could take a look at those errors?

Or maybe @PatrickSampaioUSP can help us here as well

**Comment by giovaniceotto** [comment]
Good news is that I have already started to look at this and had no severe issues (just had to add `%matplotlib widget` to make sure all animations worked fine).

However, we still need to tweak a few things such as figure size or axes limites to make everything look perfect. I am working on this and will submit some commits later.

**Comment by giovaniceotto** [comment]
I am also downloading the dataset that we will use for Spaceport America Cup. It will feature hourly data and 20 years of history. I had to break it up into 11 different requests due to limitations of the CDS API.

**Comment by giovaniceotto** [comment]
I will go ahead and merge this one since the notebook is working fine already. The remaing tweaks regard individiual functions.

**Review by giovaniceotto — APPROVED** [review]

**Pull request merged**
