### PR TITLE
doc: setting inputs and discrete intervals for Function objects on SolidMotor

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type
- [X] Code maintenance (refactoring, formatting, renaming, tests)

## Pull request checklist

- Code base maintenance (refactoring, formatting, renaming):

  - [X] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?
As described on #42 , some plots of SolidMotor.allInfo() are currently being set as Scalar x functions functions instead of Time (s) x Variable functions.

## What is the new behavior?
Now all graphs from SolidMotor.allInfo() have the 'x' axis well defined by the setInputs method

## Does this introduce a breaking change?
- [X] No

## Other information

Please verify if setDiscrete is not breaking other parts of our code. As far as I understand, the Function.setDiscrete converts functions into lists, so perhaps it will create a bug that I didn't find locally.

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Well, everything look fine here, I performed basic simulations using the modified files for checking.

@MrGribel could ypu please review this as you better understand SolidMotor class?

**Comment by MrGribel** [comment]
@Gui-FernandesBR could you clarify a bit what you're trying to solve here? Those changes don't make much sense to me at a first glance. The altered functions already seem to display the correct axes names on `develop`. This should have been changed at the branch which PR #42 provides from. Also, since all the changed plots already provide in some form from `thrust` or `grainInnerRadius`, which are already list-defined rocketpy Functions, applying the `setDiscrete` over them seems redudant.

Let me know if there is something I am missing here.

**Comment by Gui-FernandesBR** [comment]
See Function.py to correct problems

**Comment by giovaniceotto** [comment]
@Gui-FernandesBR, I did some digging here and strongly believe that all the issues that this PR attempts to solve are fixed with the simple 1 line PR #141.

It was a simple mistake I made a while back, in the Function class... my fault.

**Pull request closed without merging**
