### PR TITLE
SolidMotor_class_usage

### PR DESCRIPTION
**Pull request by lucasfourier**
Finished the SolidMotor_class_usage python notebook with examples and explanations.

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
@lucasfourier can you please take 15min to finnish this implementation and allows us to finally 

Otherwise, can @Projeto-Jupiter/public-relations-outreach fix this one?

**Comment by Gui-FernandesBR** [comment]
See Function.py to correct problems

**Comment by giovaniceotto** [comment]
I made slight changes when checking #141. Here is my file as a suggestion. Mostly fixed file paths.

[SolidMotor_class_usage.zip](https://github.com/Projeto-Jupiter/RocketPy/files/8085334/SolidMotor_class_usage.zip)

**Comment by Gui-FernandesBR** [comment]
@giovaniceotto I can't merge since you have requested changes.

Please aprove and merge, I think we are ready now!

Also, many thanks for the help here

**Review by giovaniceotto — APPROVED** [review]
I approve of this first version, but there is more to come!

In a future Pull Request, here are the things which still need to be documented:
- Working with `.eng` files: importing and exporting
- Modifying the thrust curve by using the reshape argument (should this argument be converted into a function, perhaps?)
- Explaining what the main arguments mean (grain geometry)

**Pull request merged**
