### PR TITLE
Enh/acceptance tests fixtures

### PR DESCRIPTION
**Pull request by giovaniceotto**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`python setup.py install`) was run locally and any changes were pushed
- [ ] Lint (`black rocketpy`) has passed locally and any fixes were made for failures
- [ ] All tests (`pytest --runslow`) have passed locally

## Pull request type
 
 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

RocketPy does not yet run acceptance tests.

## What is the new behavior?

Data from 3 real flights and their corresponding simulation are added as test fixtures.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by giovaniceotto** [comment]
@Projeto-Jupiter/general Could you confirm that we have the right to use Bella Lui and NDRT 2020 flight data to perform acceptance tests of every new RocketPy version?

**Comment by giovaniceotto** [comment]
@PatrickSampaioUSP It seems that GitHub Action tests are failing due to a problem with files stored using Git LFS. Travis is working fine though.

**Comment by Gui-FernandesBR** [comment]
@giovaniceotto , 
No, we cannot confirm, once we do not have such permission

**Comment by giovaniceotto** [comment]
Due to the problems related to Git LFS, I am deleting this PR and it's branch. The material presented here will be added through a new PR without Git LFS.

**Pull request closed without merging**
