### PR TITLE
ENH: Environment Analysis - Animations to Grids

### PR DESCRIPTION
**Pull request by giovaniceotto**
## Pull request type

Please check the type of change your PR introduces:

- [x] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- Code base additions (for bug fixes / features):

  - [ ] Tests for the changes have been added
  - [x] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

A complete set of wind roses can only be seen in an animation created by `EnviornmentAnalysis.animate_average_wind_rose`.

## What is the new behavior?

`EnvironmentAnalysis.plot_average_wind_rose_all_hours` method can generate a grid of wind roses as shown below. The number of rows and columns is automatically calculated by the `EnvironmentAnalysis._find_two_closest_integer_factors` method.

output

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
idk why but the code isn't working for me. I will save the error here by now and try to better understand it tomorrow: 

image

**Comment by giovaniceotto** [comment]
- [ ] Add % to radial labels
- [ ] Fix Gui's error

**Comment by giovaniceotto** [comment]
@PatrickSampaioUSP, ready for final review.

Final result:

output (3)

**Review by Gui-FernandesBR — APPROVED** [review]
Everything is working fine here, well done!!

Feel free to merge it

**Pull request merged**
