### PR TITLE
Typofix/solid motor

### PR DESCRIPTION
**Pull request by ompro07**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`python setup.py install`) was run locally and any changes were pushed
- [ ] Lint (`black rocketpy`) has passed locally and any fixes were made for failures
- [ ] All tests (`pytest --runslow`) have passed locally

## Pull request type
 
 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

RocketPy's code did not have any unit tests setup.

## What is the new behavior?

- 
- 

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- 
-

### CODE REVIEW

**Comment by ompro07** [comment]
Fixed some typos in the SolidMotor class

**Comment by Gui-FernandesBR** [comment]
Hey @ompro07 , thanks for pulling those tpos corrections, nice job.

Before merging the PR, I would like to ask you to add your name as an author in the 3rd line. Would you please?

**Review by giovaniceotto — APPROVED** [review]

**Comment by ompro07** [comment]
I add my name as requested, thanks

**Review by giovaniceotto — APPROVED** [review]
Great contribution! Thanks!

**Pull request merged**
