### PR TITLE
Check for optional package requirement: netCDF4

### PR DESCRIPTION
**Pull request by skrobchik**
## Pull request type

Please check the type of change your PR introduces:

- [x] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [ ] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

- Code base maintenance (refactoring, formatting, renaming):

  - [ ] Docs have been reviewed and added / updated if needed
  - [x] Lint (`black rocketpy`) has passed locally and any fixes were made
  - [x] All tests (`pytest --runslow`) have passed locally

## What is the current behavior?

When following tutorials, one will run a function which requires an optional dependency "netCDF4". Neither errors nor beginner tutorial communicates that it has to be installed. 

## What is the new behavior?

Functions that require netCDF4 will now tell that with a comprehensive error message to the user.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Gui-FernandesBR** [comment]
Thanks skrobchik!

@MrGribel could you please take a look with me, review and then merge it if ready?

**Comment by giovaniceotto** [comment]
I believe we would need to merge this PR into the `develop branch, rather than the master branch. @MrGribel, do you agree?

**Comment by skrobchik** [comment]
@giovaniceotto should I close this PR and open another one or is there a way to change the branch?

**Comment by skrobchik** [comment]
Thank you @lucasfourier

**Review by MrGribel — APPROVED** [review]
Thanks for this @skrobchik. We've had been planning on adding it to the default installation as an optional dependency or even migrating away from netCDF4 altogether, but this is as good as it gets for now.

Linter seems to be complaining but I think it's due to it not using the latest version of black during tests, so no worries.

**Pull request merged**
