### PR TITLE
Docs/Add functionalities to ReadMe

### PR DESCRIPTION
**Pull request by giovaniceotto**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Build (`python setup.py install`) was run locally and any changes were pushed
- [x] Lint (`black rocketpy`) has passed locally and any fixes were made for failures
- [x] All tests (`pytest --runslow`) have passed locally

## Pull request type
 
 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

ReadMe does not describe what are the main functionalities of RocketPy.

## What is the new behavior?

ReadMe clearly states all main functionalities of RocketPy.

- Nonlinear 6 degrees of freedom simulations
  - Solved using LSODA with adjustable error tolerances
- Rigorous treatment of mass variation effects
- Barrowman equations for lift coefficients (optional)
- Parachutes with external trigger functions
  - Test the exact code that will fly
  - Sensor data can be augmented with noise
- Solid motors models:
  - Burn rate and mass variation properties from thrust curve
- Accurate weather modeling
  - International Standard Atmosphere (1976)
  - Custom atmospheric profiles
  - Soundings (Wyoming, NOAARuc)
  - Weather forecasts and reanalysis
  - Weather ensembles
- Monte Carlo simulations for dispersion and sensitivity analysis
- Flexible and modular
  - Multi-stage rockets
  - Non-standard flights (e.g. parachute drop test from helicopter)
  - Custom continuos and discrete control laws
  - Easy to create new classes (e.g. other types of motors)

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by giovaniceotto** [comment]
In the future, I believe we could setup example notebooks to display each of the main features and then convert them to links for these notebooks.

Another idea is to create a subsection just after **Main Features** for **Roadmap**, where we would list the most important features being worked on (and they could link to the related PR).

**Review by PatrickSampaioUSP — APPROVED** [review]

**Review by Gui-FernandesBR — CHANGES_REQUESTED** [review]
Hi Giovani, I have some simples requests about this PR.

**Mandatory:** 
- Please correct line 31 to "Custom continuous ...".

**Non-Mandatory:**

- I suggest you to add some lines about analyses that can be done through RocketPy (e.g. Apogee by mass, Lifting off speed by mass, etc.).
- Also, since you're citing lift coefficients (line 15) maybe it would be good having some comments on drag coefficients as well.

**Comment by Gui-FernandesBR** [comment]
Hey @giovaniceotto , 
I appreciate your corrections. 
However, you last commit was caught in one of our lint test.
We must investigate this before merging.

**Comment by giovaniceotto** [comment]
@Gui-FernandesBR, the reason for this is a problem with a different part of the code, being fixed by #77. I believe we can skip the check for this one, which only changes the ReadMe file.

I hope you can accept the PR.

**Pull request merged**
