### PR TITLE
FIX: fixing docs error - 3rd attempt

### PR DESCRIPTION
**Pull request by giovaniceotto**
# Pull request type

Please check the type of change your PR introduces:

- [ ] Code base additions (bugfix, features)
- [ ] Code maintenance (refactoring, formatting, renaming, tests)
- [x] ReadMe, Docs and GitHub maintenance
- [ ] Other (please describe):

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [x] Spelling has been verified
  - [x] Code docs are working correctly

## What is the current behavior?

Code documentation is empty: https://docs.rocketpy.org/en/latest/reference/classes/Function.html

## What is the new behavior?

- Fixes empty code documentation (by setting up a read the docs configuration file, setting it up to use python 3.9 instead of python 3.7 (required by Environment Analysis) and requesting it to install the requirements).

- Adds Environment Analysis code documentation.

Preview: https://docs.rocketpy.org/en/hot_fix_documentation/reference/classes/Function.html

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Gui-FernandesBR — APPROVED** [review]

**Comment by Gui-FernandesBR** [comment]
it was working perfectly on preview, but final version wasn't that good after merging...


image

**Comment by Gui-FernandesBR** [comment]
Sorry too quick comment.. it takes a time until docs page refresh ... docs are passing but not all the classes are working on the code reference:

image

image

image

**Comment by giovaniceotto** [comment]
It is probably due to cache. Check on your phone or an incognito tab.

**Comment by Gui-FernandesBR** [comment]
Ok thanks for the tip, it's working fine and correctly now!

**Pull request merged**
