### PR TITLE
Prepare master to v0.10.0 release

### PR DESCRIPTION
**Pull request by Gui-FernandesBR**
## Pull request type

Please check the type of change your PR introduces:
- [X] ReadMe, Docs and GitHub maintenance

## Pull request checklist

Please check if your PR fulfills the following requirements, depending on the type of PR:

- ReadMe, Docs and GitHub maintenance:

  - [X] Spelling has been verified
  - [X] Code docs are working correctly 

## What is the current behavior?
Our current master branch is outdated, we need to fill it with the good resources (code lines!) we have created on develop branch. By doing this, we will be able to  reaease the next version of rocketpy package!

## What is the new behavior?
44 commits from develop being merged into master branch. Differences will be further described on release notes.

## Does this introduce a breaking change?
- [X] No

### CODE REVIEW

**Review by giovaniceotto — APPROVED** [review]

**Comment by giovaniceotto** [comment]
@Gui-FernandesBR, whatever the conflict is, keep the version in `develop`. Let me know if you need help. Approved to merge.

**Comment by Gui-FernandesBR** [comment]
> @Gui-FernandesBR, whatever the conflict is, keep the version in `develop`. Let me know if you need help. Approved to merge.

Yeah I need help.

Can't merge before finding why is pytest jobs crashing on this PR... My guess is that we are having this due to v0.10.0 code lines, since we didn't already published a package with this version name

**Comment by Gui-FernandesBR** [comment]
image

screenshoot I got from travisCI webpage

**Comment by giovaniceotto** [comment]
Discord

**Pull request merged**
